# Generated by Django 6.0.3 on 2026-03-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='total_amount',
            field=models.FloatField(blank=True),
        ),
    ]
