# Generated by Django 6.0.3 on 2026-03-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_dashboardlayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='street_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='country',
            field=models.CharField(choices=[('USA', 'United States'), ('CAN', 'Canada'), ('GBR', 'United Kingdom'), ('IND', 'India'), ('AUS', 'Australia'), ('DEU', 'Germany'), ('FRA', 'France'), ('BRA', 'Brazil'), ('JPN', 'Japan'), ('ZAF', 'South Africa')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='created_by',
            field=models.CharField(choices=[('admin', 'Admin'), ('Ramprasad', 'Ramprasad'), ('Sabari', 'Sabari'), ('Prabha', 'Prabha'), ('Sanjay', 'Sanjay')], default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='product',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Smartphone', 'Smartphone'), ('Headphones', 'Headphones'), ('Camera', 'Camera'), ('Smartwatch', 'Smartwatch'), ('Tablet', 'Tablet'), ('Monitor', 'Monitor'), ('Printer', 'Printer'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('fiber_300', 'Fiber Internet 300 Mbps'), ('5g_unlimited', '5G Unlimited Mobile Plan'), ('fiber_1gb', 'Fiber Internet 1 Gbps'), ('business_500', 'Business Internet 500 Mbps'), ('voip_corporate', 'VoIP Corporate Package')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled')], max_length=50),
        ),
    ]
